chore: Updating tractusx file
eclipse-tractusx/sd-factory pull request #101
Opened 2024-02-22 07:27 UTC by adkumar1

- Resolves #96 
-  Updated the header in .tractusx file

2024-02-22 12:29 UTC, evegufy requested changes
@adkumar1 could you please rebase your branch to main to that only the relevant change is shown?

2024-02-22 15:53 UTC, adkumar1 commented
Did the rebase.
Please merge PR #99 before this

2024-02-23 07:10 UTC, adityagajbhiye9 approved these changes
LGTM

2024-02-23 10:31 UTC, evegufy approved these changes

2024-02-23 10:32 UTC, merged