QG5 changes
eclipse-tractusx/sd-factory pull request #21
Opened 2023-02-16 10:12 UTC by adkumar1

2023-02-16 11:09 UTC, carslen requested changes
Good job, we're making progress! 

Please: 
- add missing `charts/SDFactory/Readme.md` file. You can use [helm-docs](https://github.com/norwoodj/helm-docs) to generate it. This is a good time to add valuable comments to your `values.yaml` file, as helm-docs will add the comment to the description field.
- resolve the requested changes (refer to comments), there are a few

2023-02-17 06:50 UTC, adkumar1 commented on CHANGELOG.md
>  QG5 changes
Fixed it.

2023-02-17 06:51 UTC, adkumar1 commented on CHANGELOG.md
> +## [1.2.1] - 2023-02-16
Fixed it.

2023-02-17 06:51 UTC, adkumar1 commented on INSTALL.md
> +
There are no dependencies in this application. so we are good

2023-02-17 06:52 UTC, adkumar1 commented on README.md
> +1.) Using helm commands:- <br />
Created the link.

2023-02-17 06:52 UTC, adkumar1 commented on charts/SDFactory/.helmignore
> +.vscode/
Changed the content

2023-02-17 07:12 UTC, carslen commented on CHANGELOG.md
>  QG5 changes
Better, but I'm still missing the Added/Changed/Fixed/... sections for 1.2.0.

2023-02-17 07:13 UTC, carslen commented on CHANGELOG.md
> +## [1.2.1] - 2023-02-16
Better, but I'm still missing the Added/Changed/Fixed/... sections for 1.2.1.

2023-02-17 07:15 UTC, carslen commented on README.md
> +1.) Using helm commands:- <br />
Perfect. Please remove the ":-"  in the headline

2023-02-17 07:23 UTC, carslen commented
Please add the missing `charts/SDFactory/Readme.md` file (use helm-docs to generate the file and add valuable comments to `charts/SDFactory/values.yaml`). 

If this file has been added (incl. the comments in `values.yaml`) and the few open remarks got solved, then we're good to go.

2023-02-17 08:41 UTC, adkumar1 commented on CHANGELOG.md
> +## [1.2.1] - 2023-02-16
Done! Segregated the added, changed

2023-02-17 08:41 UTC, adkumar1 commented on README.md
> +1.) Using helm commands:- <br />
Removed

2023-02-20 08:21 UTC, carslen approved these changes

2023-02-20 08:38 UTC, carslen commented
I'll merge this now, although GitGuardian complains. Found creds where example ones and removed

2023-02-20 08:38 UTC, merged