feat: Refactoring the SD-Factory
eclipse-tractusx/sd-factory pull request #71
Opened 2023-10-05 12:03 UTC by adkumar1

- Refactoring the SD-Factory to support number of formats (Catena-22-10, GaiaX, FC) as output. 
-  It shall be fully compatible on level of Catena-22-10 with previous versions. 
- Creates a payload and send it unsigned to the CH

2023-10-06 06:05 UTC, almadigabor requested changes

2023-10-06 06:05 UTC, almadigabor commented on DEPENDENCIES
Please open IP issue tickets for restricted dependencies.

2023-10-06 11:29 UTC, dvasunin commented on DEPENDENCIES
yes, we have some libraries marked as "restricted" due to the version upgrade. Can you please raise the tickets for us as we do not have "committer" priviledges.

2023-10-09 08:21 UTC, almadigabor commented
I was running the dash tool and got the following output. Please track the generated IP issue tickets found below in the links:

```
[INFO] This content is either not correctly mapped by the system, or requires review.
[INFO] A review is required for maven/mavencentral/com.danubetech/key-formats-java/1.6.0.
[INFO] A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10950 .
[INFO] A review is required for maven/mavencentral/info.weboftrust/ld-signatures-java/1.2.0.
[INFO] A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10951 .
[INFO] A review is required for maven/mavencentral/com.goterl/lazysodium-java/5.1.1.
[INFO] A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10952 .
[INFO] A review is required for maven/mavencentral/com.danubetech/verifiable-credentials-java/1.1.0.
[INFO] A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10953 .
[INFO] A review is required for maven/mavencentral/decentralized-identity/jsonld-common-java/1.1.0.
[INFO] A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10954 .
```

2023-10-10 08:02 UTC, almadigabor commented on DEPENDENCIES
sure, tickets were raised, see them in the comments

2023-10-17 06:56 UTC, almadigabor commented
I'll merge this commit but release must not be created from this as the `DEPENDENCIES` file contains restricted libraries (with IP issue numbers).

2023-10-17 07:01 UTC, merged